# timemachine — JACK retrospective audio capture
#
# Dependencies: jack, sndfile, liblo, gtk+-2.0, readline, pthread
# Build:   make
# Test:    make test
# Install: make install PREFIX=/usr/local
# Clean:   make clean

PREFIX  ?= /usr/local
BINDIR  ?= $(PREFIX)/bin
DATADIR ?= $(PREFIX)/share

BUILD   := build
SRCDIR  := src

# ---- toolchain ----

CC      ?= gcc
CFLAGS  ?= -O2 -Wall -Wno-deprecated-declarations
LDFLAGS ?=

# ---- dependencies (pkg-config) ----

PKG_DEPS := jack sndfile liblo gtk+-2.0

PKG_CFLAGS := $(shell pkg-config --cflags $(PKG_DEPS))
PKG_LIBS   := $(shell pkg-config --libs $(PKG_DEPS))

# ---- feature detection ----
#
# liblo is mandatory.  readline, W64, FLAC are detected.
# LASH is gone.

# readline: default yes. Set HAVE_READLINE=no if not installed.
# TODO(CLAUDE): Fix readline auto-detection. The $(shell) compile test
# works from the terminal but fails inside Make's $(shell). Probably a
# SHELL or environment issue. This needs to be fixed before publishing —
# defaulting to yes is fine for local builds but will break on systems
# without readline. DO NOT SHIP THIS WITHOUT FIXING IT.
HAVE_READLINE ?= yes

# ---- defines ----

DEFINES := -DHAVE_CONFIG_H \
           -DPACKAGE=\"timemachine\" \
           -DPACKAGE_DATA_DIR=\"$(DATADIR)\" \
           -DHAVE_LIBLO

ifeq ($(HAVE_READLINE),yes)
  DEFINES += -DHAVE_LIBREADLINE
  READLINE_LIBS := -lreadline
else
  $(warning readline not found — console mode disabled)
  READLINE_LIBS :=
endif

# ---- sources ----

SRCS := main.c threads.c callbacks.c interface.c \
        support.c gtkmeter.c gtkmeterscale.c meters.c

OBJS := $(SRCS:%.c=$(BUILD)/%.o)

# ---- targets ----

.PHONY: all clean test install config

all: $(BUILD)/config.h $(BUILD)/timemachine
	@echo "build complete: $(BUILD)/timemachine"

$(BUILD)/timemachine: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^ $(PKG_LIBS) $(READLINE_LIBS) -lpthread -lm

$(BUILD)/%.o: $(SRCDIR)/%.c $(BUILD)/config.h | $(BUILD)
	$(CC) $(CFLAGS) $(DEFINES) $(PKG_CFLAGS) -I$(BUILD) -c -o $@ $<

$(BUILD):
	mkdir -p $(BUILD)

# ---- config.h generation ----
#
# Detect optional sndfile format support (W64, FLAC) at build time.
# config.h is included via HAVE_CONFIG_H / #include "config.h".

$(BUILD)/config.h: | $(BUILD)
	@echo "generating $@"
	@echo "/* generated by make — do not edit */" > $@
	@echo "#ifndef CONFIG_H"                      >> $@
	@echo "#define CONFIG_H"                       >> $@
	@echo "#define PACKAGE \"timemachine\""         >> $@
	@echo "#define PACKAGE_DATA_DIR \"$(DATADIR)\"" >> $@
	@echo "#define HAVE_LIBLO 1"                   >> $@
	@if echo '#include <sndfile.h>' | $(CC) $(PKG_CFLAGS) -x c -E - 2>/dev/null \
	    | grep -q SF_FORMAT_W64; then \
	    echo "#define HAVE_W64 1" >> $@; \
	    echo "  W64: yes"; \
	else \
	    echo "  W64: no"; \
	fi
	@if echo '#include <sndfile.h>' | $(CC) $(PKG_CFLAGS) -x c -E - 2>/dev/null \
	    | grep -q SF_FORMAT_FLAC; then \
	    echo "#define HAVE_FLAC 1" >> $@; \
	    echo "  FLAC: yes"; \
	else \
	    echo "  FLAC: no"; \
	fi
	@if [ "$(HAVE_READLINE)" = "yes" ]; then \
	    echo "#define HAVE_LIBREADLINE 1" >> $@; \
	    echo "  readline: yes"; \
	else \
	    echo "  readline: no"; \
	fi
	@echo "#endif /* CONFIG_H */" >> $@

# ---- tests ----

TEST_SRCS := $(wildcard tests/*.c)
TEST_BINS := $(TEST_SRCS:tests/%.c=$(BUILD)/%)

test: $(TEST_BINS)
	@echo "running tests"
	@echo "-----------------------------"
	@fail=0; \
	for t in $(TEST_BINS); do \
	    if $$t; then \
	        echo "PASS: $$(basename $$t)"; \
	    else \
	        echo "FAIL: $$(basename $$t)"; \
	        fail=1; \
	    fi; \
	done; \
	echo "-----------------------------"; \
	exit $$fail

$(BUILD)/%: tests/%.c | $(BUILD)
	$(CC) $(CFLAGS) -o $@ $< -lm

# ---- install ----

install: $(BUILD)/timemachine
	install -d $(DESTDIR)$(BINDIR)
	install -m 755 $(BUILD)/timemachine $(DESTDIR)$(BINDIR)/timemachine
	install -d $(DESTDIR)$(DATADIR)/timemachine/pixmaps
	install -m 644 pixmaps/*.png $(DESTDIR)$(DATADIR)/timemachine/pixmaps/

# ---- clean ----

clean:
	rm -rf $(BUILD)
